src/Team12/Team12/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views


urlpatterns = [
    path('', views.index , name='Index'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('products/', include('product.urls')), # url for product page
    path('cart/', include('cart.urls')) # url for cart inspection
]

src/Team12/cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.index, name='cart'),
    path('add/', views.add, name='add_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('delete/', views.delete, name="delete"),
    path('edit_quantity/', views.edit_quantity, name="edit_quantity"),
    path('edit_size/', views.edit_size, name="edit_size"),
    path('change_quantity/', views.change_quantity, name="change_quantity"),
    path('subscribe/', views.subscribe, name="subscribe")
]

src/Team12/product/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name='products'

urlpatterns = [
    path('', views.index , name='index'),
    path('filter_price/<int:filter>/<int:filter2>/', views.filter_price, name='filter_price'), # url takes in two prices 
    path('mealplan/<int:pk>/', views.detailed_product, name='detailed'), # url takes the primary key of a product
    path('product_order/<str:order>/', views.product_order , name='product_order'), # url takes in price or -price (the latter meaning descending ordering)
]

src/Team12/product/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext as _

class MealPlan(models.Model):

    name        = models.CharField(max_length=50)
    price       = models.IntegerField()
    recipe      = models.TextField(blank=False)
    ingredients = models.TextField(blank=False, default="N/A")
    image       = models.CharField(max_length=255)

    objects     = models.Manager()

    class Meta:
        verbose_name = _("meal plan")
        verbose_name_plural = _("meal plans")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("MealplanDetailed", kwargs={"pk": self.pk})
        # return reverse_lazy('MealplanDetailed', kwargs={'pk': self.pk}, current_app='products')

src/Team12/product/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import MealPlan

def index(request):
    data = MealPlan.objects.all() # simple index which draws all meal plans from the database

    context = {
        "products": data,
    }

    return render(request, 'products/index.html', context)

def detailed_product(request, pk): # A detailed product is genereated by primary key id
    meal_plan = get_object_or_404(MealPlan, pk=pk)

    context  = {
        "mealplan": meal_plan,
    }

    return render(request, 'products/mealplan_detailed.html', context)


def product_order(request, order):
    data = MealPlan.objects.order_by(order).all() # Here the product gets ordered in accending or descending order dependingon the def input var

    context = {
        "products": data,
    }

    return render(request, 'products/index.html', context)

def filter_price(request, filter, filter2):
    data = MealPlan.objects.filter(price__gte = filter, price__lte = filter2) # The mealplan get filtered by two parameters (Greater less and equal)

    context = {
        "products": data,
    }

    return render(request, 'products/index.html', context)

src/Team12/templates/products/index.html
{% extends 'base.html' %}
{% block content %}
<button type="button"> <a class="nav-link" href="{% url 'products:product_order' '-price' %}">Sort by Highest Price</a> </button>
<button type="button"> <a class="nav-link" href="{% url 'products:product_order' 'price' %}">Sort by Lowest Price</a> </button>
<br><br>
<a> Price Ranges </a><br>
<button type="button"> <a class="nav-link" href="{% url 'products:filter_price' filter=0 filter2=4999 %}">0.Kr - 4.999Kr</a> </button>
<button type="button"> <a class="nav-link" href="{% url 'products:filter_price' filter=5000 filter2=9999 %}">5.000Kr - 9.999Kr</a> </button>
<br>
<button type="button"> <a class="nav-link" href="{% url 'products:filter_price' filter=10000 filter2=14999 %}">10.000Kr - 14.999Kr</a> </button>
<button type="button"> <a class="nav-link" href="{% url 'products:filter_price' filter=15000 filter2=19999 %}">15.000Kr - 19.999Kr</a> </button>
<br>
<button type="button"> <a class="nav-link" href="{% url 'products:filter_price' filter=20000 filter2=24999 %}">20.000Kr - 24.999Kr</a> </button>
<button type="button"> <a class="nav-link" href="{% url 'products:filter_price' filter=25000 filter2=29999 %}">25.000Kr - 29.999Kr</a> </button>




{% for product in products %}
    <div style="border: solid black; text-align: center;">
        <a href="{% url 'products:detailed' product.pk %}">
            <h3>Name: {{ product.name}}</h3>
            <h3>Price: {{ product.price }}</h3>
            {% comment %} <h3>Recipe: {{ product.recipe }}</h3> {% endcomment %}
            {% comment %} <h3>ingredients: {{ product.ingredients }}</h3> {% endcomment %}
            <img src="{{product.image}}" style='max-width: 100%; max-height: 100%;'>
            {% comment %} <h3>image: {{ product.image }}</h3> {% endcomment %}
        </a>
    </div>
{% endfor %}
{% endblock %}

src/Team12/templates/products/mealplan_detailed.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ mealplan.name}}</h1>
    <div style="display: flex;">
        <div style="flex: 0 60%;">
            <img src="{{mealplan.image}}" style='max-width: 500px; max-height: 100%;'>
        </div>

        <div style="flex: 1;">
            <h2>Price: {{ mealplan.price }}</h2>
        </div>
    </div>
    
    <p>
        <h2>Ingredients</h2> <br>
        <a>{{ mealplan.ingredients }}</a> <br>
        <h2>Recipe</h2> <br>
        <a>{{ mealplan.recipe }}</a> <br>
        <h2>Allergies</h2>
        <a>{{ mealplan.allergies }}</a>
    </p>
    <div>
        <form
            {% if user.is_authenticated %}
                action="{% url 'cart:add_item' %}"
            {% else %}
                action="#"
            {% endif %}
            method="POST">
            {% csrf_token %}
            
            <input type="number" name="size" value=1 min=1 max=3>
            <label for="size">Size</label><br>
            <input type="number" name="quantity" value=1 min=1 max=10>
            <label for="quantity">Quantity</label>
            <br>
            <button type="submit" name="id" value={{ mealplan.id }}>
                Add to cart
            </button>
        </form>
        <form
            {% if user.is_authenticated %}
                action="{% url 'cart:subscribe' %}"
            {% else %}
                action="#"
            {% endif %}
            method="POST">
            {% csrf_token %}
            <button type="submit" name="id" value={{ mealplan.id }}>
                Subscribe
            </button>
        </form>
    </div>
{% endblock %}