src/Team12/Team12/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views


urlpatterns = [
    path('', views.index , name='Index'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('products/', include('product.urls')), # url for product page
    path('cart/', include('cart.urls')) # url for cart inspection
]

src/Team12/cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.index, name='cart'),
    path('add/', views.add, name='add_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('delete/', views.delete, name="delete"),
    path('edit_quantity/', views.edit_quantity, name="edit_quantity"),
    path('edit_size/', views.edit_size, name="edit_size"),
    path('change_quantity/', views.change_quantity, name="change_quantity"),
    path('subscribe/', views.subscribe, name="subscribe")
]

src/Team12/product/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name='products'

urlpatterns = [
    path('', views.index , name='index'),
    path('filter_price/<int:filter>/<int:filter2>/', views.filter_price, name='filter_price'), # url takes in two prices 
    path('mealplan/<int:pk>/', views.detailed_product, name='detailed'), # url takes the primary key of a product
    path('product_order/<str:order>/', views.product_order , name='product_order'), # url takes in price or -price (the latter meaning descending ordering)
]

src/Team12/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  
  <title>Team12</title>
</head>
<body style="width=100%;">

  <header>
    {% include 'navbar.html' %}
  </header>
  
  {% include 'cart_preview.html' %}
  
  <main role="main" class="container" style="padding-top:80px; padding-bottom: 10px; min-height: calc(100vh - 56px);">
    {% block content %}
      <p>ELLO</p>
    {% endblock %}
  </main>

  <footer class="footer mt-auto py-3" style="color:rgb(230,230,230); background-color: rgb(20,20,20);">
    <div class="container">
      <a>Developed by Team12 all rights reserved &copy {% now "Y" %}</span></a>
    </div>
  </footer> 

<!-- jQuery CDN - Slim version (=without AJAX) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

<!-- Popper.JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<!-- jQuery Custom Scroller CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

</body>
</html>

<style>
.html {
  position: relative;
  min-height: 100%;
}

</style>

<script>
  function toggleCart() {
    var navbar = document.getElementById("the-header");
    var cart = document.getElementById("cart-preview");
    var cartWidth = parseInt(cart.style.width);
    if (parseInt(cart.style.right) < 0) { 
      cart.style.right = "0";
      navbar.style.right = String(cartWidth) + "px";
    } else { 
      cart.style.right = String(-cartWidth) + "px";
      navbar.style.right = "0";
    }
  }

  function clickOfCart(e) {
    // Get viewport width
    var vw = Math.max(document.documentElement.clientWidth || 0, window.innerWidth || 0)
    var cart = document.getElementById("cart-preview").style // Cart preview panel

    if (parseInt(cart.right) < 0) { return; } // If it is closed return

    // Else toggle it down if user clicks off it
    if (!((-vw + e.clientX) > (parseInt(cart.right) - parseInt(cart.width)))) {
      toggleCart();
    }
  }

  document.addEventListener("click", clickOfCart);

</script>

src/Team12/templates/cart_preview.html
{# Cart preview #}
<div id="cart-preview" class="container bg-white border-left" 
style="
  position: fixed; 
  right: -999px; 
  z-index: 1030; 
  width: 400px; 
  min-height: 100vh; 
  transition: right 0.5s ease;"
>
  <h3 class="p-1"> Your Cart
  <a class="btn-sm btn-light" href="{% url 'cart:cart' %}">Go to cart</a>
    <button type="button" class="close" href="javascript:void(0)" onclick="toggleCart()">
      <span >&times;</span>
    </button>
  </h3>
  

  {% if cart and cart_items %}
  {# Items #}
  <div class="list-group list-group-flush">

    {% for item in cart_items %}

      <div class="border-top d-flex flex-row bg-white">
        {# Item pic #}
        <div class="p-2">
          <img src="{{ item.mealplan.image }}" height="60px" width="60px" style="object-fit: cover;">
        </div>
        {# Item name, price #}
        <div class="p-2" style="width:160px;">
          <p class="m-0 font-weight-bold"> {{item.mealplan.name}} </p>
          <p class="m-0"> Price: {{item.get_price}} ISK</p>
        </div>
        <form class="d-flex align-items-center" action="{% url 'cart:change_quantity' %}" method="post">
          {% csrf_token %}

            <input class="p-1" type="number" name="quantity" value="{{item.quantity}}" style="width:50px; height:30px;">
            <button class="p-1 btn btn-light " type="submit" name="id" value="{{ item.mealplan.id }}" style="margin-left:5px; font-size:0.8em; height:30px;">OK</button>

        </form>
        {# Remove from cart #}
        <form class="ml-auto align-self-start" action="{% url 'cart:delete' %}" method="post">
          {% csrf_token %}
          <button type="submit" name="id" value="{{ item.mealplan.id }}" style="padding:5px; height:30px; border:0; background-color:inherit;">
            <svg class="align-top" width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              <path fill-rule="evenodd" d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
            </svg>
          </button>
        </form>
      </div>
    
    {% endfor %}

  </div>
  {# Total and checkout #}
  <div class="border-top">
  Total price: <b>{{ cart.total_price }} </b> ISK
  </div>
  <a href="{% url 'cart:checkout'%}">
    <div class="btn-lg btn-success text-center" >
    Checkout
    </div>
  </a>
  {% else %}
  {# Cart is empty #}
  <h3>
      Your cart seems to be empty.<br>
      Go buy something!<br>
      Please...
  </h3>
  {% endif %}
  
</div>

src/Team12/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'Index' %}">Site name</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'products:index' %}">Products</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart' %}">Cart</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Logout' %}">{% if user.get_username %}Log out{% else %}Log in
                {% endif %}</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>